version: '3.9'

services:
  postgres:
    image: postgres:17.2
    container_name: my_postgres
    env_file:
      - ./environment/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: my_pgadmin
    env_file:
      - ./environment/.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./environment/servers.json:/pgadmin4/servers.json

  python_app:
    build:
      context: ./python_script
    container_name: my_python_script
    depends_on:
      - postgres
    volumes:
      - ./python_script:/script

volumes:
  postgres-data:
