name: smartETL

services:
  postgres:
    image: postgres:17.2
    container_name: dor_postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      dor_network:
        aliases:
          - dor_network

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: dor_pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - ./conf/postgresql/servers.json:/pgadmin4/servers.json
    networks:
      dor_network:
        aliases:
          - dor_network

  python_app:
    container_name: dor_scripts
    build:
      context: .
      dockerfile: pythonApp.Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - ./data:/data
    networks:
      dor_network:
        aliases:
          - dor_network

  grafana:
    image: grafana/grafana:11.5.1
    container_name: dor_grafana
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
      - ./conf/grafana/dashboards:/import
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      dor_network:
        aliases:
          - dor_network

  airflow:
    build:
      context: .
      dockerfile: dockerfile_airflow/dockerfile
    container_name: dor_airflow
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
        - ./airflow/dags:/opt/airflow/dags
        - logs_data:/opt/airflow/logs
        - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      dor_network:
        aliases:
          - dor_network

volumes:
  postgres-data:
  grafana-data:
  logs_data:


networks:
  dor_network:
