-- author : Antoine
-- version : 0.1
-- contrib :
-- description : script de création de la table reseau full

-- suppression de la table si elle existe
DROP TABLE IF EXISTS myreport_reseau_full;

-- création de la table
CREATE TABLE IF NOT EXISTS myreport_reseau_full
(
	ident BIGSERIAL,
    Date VARCHAR(255),--il y aura un traitement à faire sur les données
    heureDate_RAW REAL,
    Somme_Volume REAL,
    Somme_Volume_RAW REAL,
    Somme_Debit REAL,
    Somme_Debit_RAW REAL,
    Trafic_Entrant_Volume REAL,
    Trafic_Entrant_Volume_RAW REAL,
    Trafic_Entrant_Debit REAL,
    Trafic_Entrant_Debit_RAW REAL,
    Trafic_Sortant_Volume REAL,
    Trafic_Sortant_Volume_RAW REAL,
    Trafic_Sortant_Debit REAL,
    Trafic_Sortant_Debit_RAW REAL,
    Paquets_Volume REAL,
    Paquets_Volume_RAW REAL,
    Paquets_Debit REAL,
    Paquets_Debit_RAW REAL,
    Paquets_Refus_Volume REAL,
    Paquets_Refus_Volume_RAW REAL,
    Paquets_Refus_Debit REAL,
    Paquets_Refus_Debit_RAW REAL,
    Paquets_Envoyes_Volume REAL,
    Paquets_Envoyes_Volume_RAW REAL,
    Paquets_Envoyes_Debit REAL,
    Paquets_Envoyes_Debit_RAW REAL,
    Monodiffusion_entrante_Volume REAL,
    Monodiffusion_entrante_Volume_RAW REAL,
    Monodiffusion_entrante_Debit REAL,
    Monodiffusion_entrante_Debit_RAW REAL,
    Monodiffusion_sortante_Volume REAL,
    Monodiffusion_sortante_Volume_RAW REAL,
    Monodiffusion_sortante_Debit REAL,
    Monodiffusion_sortante_Debit_RAW REAL,
    Paquets_non_monodiffusion_entrants_Volume REAL,
    Paquets_non_monodiffusion_entrants_Volume_RAW REAL,
    Paquets_non_monodiffusion_entrants_Debit REAL,
    Paquets_non_monodiffusion_entrants_Debit_RAW REAL,
    Paquets_non_monodiffusion_sortants_Volume REAL,
    Paquets_non_monodiffusion_sortants_Volume_RAW REAL,
    Paquets_non_monodiffusion_sortants_Debit REAL,
    Paquets_non_monodiffusion_sortants_Debit_RAW REAL,
    Erreurs_entrantes_Volume REAL,
    Erreurs_entrantes_Volume_RAW REAL,
    Erreurs_entrantes_Debit REAL,
    Erreurs_entrantes_Debit_RAW REAL,
    Erreurs_sortantes_Volume REAL,
    Erreurs_sortantes_Volume_RAW REAL,
    Erreurs_sortantes_Debit REAL,
    Erreurs_sortantes_Debit_RAW REAL,
    Entrants_rejets_Volume REAL,
    Entrants_rejets_Volume_RAW REAL,
    Entrants_rejets_Debit REAL,
    Entrants_rejets_Debit_RAW REAL,
    Sortants_rejets_Volume REAL,
    Sortants_rejets_Volume_RAW REAL,
    Sortants_rejets_Debit REAL,
    Sortants_rejets_Debit_RAW REAL,
    Protocoles_inconnus_entrants_Volume REAL,
    Protocoles_inconnus_entrants_Volume_RAW REAL,
    Protocoles_inconnus_entrants_Debit REAL,
    Protocoles_inconnus_entrants_Debit_RAW REAL,
    Temps_mort_cpu REAL,
    Temps_mort_cpu_RAW REAL,
    Couverture_cpu REAL,
    Couverture_cpu_RAW REAL
);
