-- author : Antoine
-- version : 0.1
-- contrib :
-- description : script de création de la table reseau full

-- suppression de la table si elle existe
DROP TABLE IF EXISTS myreport_reseau_full;

-- création de la table
CREATE TABLE IF NOT EXISTS myreport_reseau_full
(
	ident BIGSERIAL,
    Date VARCHAR(255),--il y aura un traitement à faire sur les données
    heureDate_RAW REAL,
    Somme_Volume VARCHAR(255),
    Somme_Volume_RAW REAL,
    Somme_Debit VARCHAR(255),
    Somme_Debit_RAW REAL,
    Trafic_Entrant_Volume VARCHAR(255),
    Trafic_Entrant_Volume_RAW REAL,
    Trafic_Entrant_Debit VARCHAR(255),
    Trafic_Entrant_Debit_RAW REAL,
    Trafic_Sortant_Volume VARCHAR(255),
    Trafic_Sortant_Volume_RAW REAL,
    Trafic_Sortant_Debit VARCHAR(255),
    Trafic_Sortant_Debit_RAW REAL,
    Paquets_Volume VARCHAR(255),
    Paquets_Volume_RAW REAL,
    Paquets_Debit VARCHAR(255),
    Paquets_Debit_RAW REAL,
    Paquets_Refus_Volume VARCHAR(255),
    Paquets_Refus_Volume_RAW REAL,
    Paquets_Refus_Debit VARCHAR(255),
    Paquets_Refus_Debit_RAW REAL,
    Paquets_Envoyes_Volume VARCHAR(255),
    Paquets_Envoyes_Volume_RAW REAL,
    Paquets_Envoyes_Debit VARCHAR(255),
    Paquets_Envoyes_Debit_RAW REAL,
    Monodiffusion_entrante_Volume VARCHAR(255),
    Monodiffusion_entrante_Volume_RAW REAL,
    Monodiffusion_entrante_Debit VARCHAR(255),
    Monodiffusion_entrante_Debit_RAW REAL,
    Monodiffusion_sortante_Volume VARCHAR(255),
    Monodiffusion_sortante_Volume_RAW REAL,
    Monodiffusion_sortante_Debit VARCHAR(255),
    Monodiffusion_sortante_Debit_RAW REAL,
    Paquets_non_monodiffusion_entrants_Volume VARCHAR(255),
    Paquets_non_monodiffusion_entrants_Volume_RAW REAL,
    Paquets_non_monodiffusion_entrants_Debit VARCHAR(255),
    Paquets_non_monodiffusion_entrants_Debit_RAW REAL,
    Paquets_non_monodiffusion_sortants_Volume VARCHAR(255),
    Paquets_non_monodiffusion_sortants_Volume_RAW REAL,
    Paquets_non_monodiffusion_sortants_Debit VARCHAR(255),
    Paquets_non_monodiffusion_sortants_Debit_RAW REAL,
    Erreurs_entrantes_Volume VARCHAR(255),
    Erreurs_entrantes_Volume_RAW REAL,
    Erreurs_entrantes_Debit VARCHAR(255),
    Erreurs_entrantes_Debit_RAW REAL,
    Erreurs_sortantes_Volume VARCHAR(255),
    Erreurs_sortantes_Volume_RAW REAL,
    Erreurs_sortantes_Debit VARCHAR(255),
    Erreurs_sortantes_Debit_RAW REAL,
    Entrants_rejets_Volume VARCHAR(255),
    Entrants_rejets_Volume_RAW REAL,
    Entrants_rejets_Debit VARCHAR(255),
    Entrants_rejets_Debit_RAW REAL,
    Sortants_rejets_Volume VARCHAR(255),
    Sortants_rejets_Volume_RAW REAL,
    Sortants_rejets_Debit VARCHAR(255),
    Sortants_rejets_Debit_RAW REAL,
    Protocoles_inconnus_entrants_Volume VARCHAR(255),
    Protocoles_inconnus_entrants_Volume_RAW REAL,
    Protocoles_inconnus_entrants_Debit VARCHAR(255),
    Protocoles_inconnus_entrants_Debit_RAW REAL,
    Temps_mort_cpu VARCHAR(255),
    Temps_mort_cpu_RAW REAL,
    Couverture_cpu VARCHAR(255),
    Couverture_cpu_RAW REAL
);
