{
 "title": "Dashboard Analytics des ETL",
 "time": { "from": "2024-10-14T22:00:00.000Z", "to": "2024-10-15T21:59:59.000Z" },
 "panels": [
  { "title": "Nb erreurs quotidiennes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nb erreurs quotidiennes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Nb erreurs quotidiennes (échelle log10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Nb erreurs hebdo (7j glissants)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Nb erreurs totales sur 7 jours glissants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', date_and_heure)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- where date_and_heure >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Nb erreurs totales sur 7 jours glissants (échelle log10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', date_and_heure)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- where date_and_heure >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
    }
   ]
  },
  { "title": "Taux d'erreur quotidien", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Taux d'erreur quotidien global",
   "type": "timeseries",
   "description": "SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations)+1)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n   SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations)+1) as \"taux d'erreur\"\nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Taux d'erreur quotidien MOYEN sur 7 jours glissants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', date_and_heure)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    \n    SUM(total_errors)::float / GREATEST(1.0,(SUM(total_errors)::float + SUM(nb_operations)::float)) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 7j\"\nFROM daily\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Taux d'erreur quotidien MOYEN sur 30 jours glissants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', date_and_heure)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / GREATEST(1.0, SUM(total_errors)::float + SUM(nb_operations)::float)   AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '29 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 30j\"\nFROM daily\nORDER BY jour;"
    }
   ]
  },
  { "title": "Par type d'erreu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Répartition par type d'erreur",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(ColumnName_Error) AS total_ColumnName_Error,\n  SUM(ConnectionTimeout_Error) AS total_ConnectionTimeout_Error,\n  SUM(CreateTABLE_Error) AS total_CreateTABLE_Error,\n  SUM(DateFormat_Error) AS total_DateFormat_Error,\n  SUM(FieldSize_Error) AS total_FieldSize_Error,\n  SUM(GuidezAtelier_Error) AS total_Guidez_Atelier_Error,\n  SUM(IndexErrorSimilarToUniqueIndex_Error) AS total_Index_Error,\n  SUM(ObjectReference_Error) AS total_ObjectReference_Error,\n  SUM(Other_Error) AS total_Other_Error,\n  SUM(PreLogin_Error) AS total_PreLogin_Error,\n  SUM(PrimaryKey_Error) AS total_PrimaryKey_Error,\n  SUM(SQLInvalidQuery_Error) AS total_SQLInvalidQuery_Error,\n  SUM(SQLQueryTimeout_Error) AS total_SQLQueryTimeout_Error,\n  SUM(TimeFormat_Error) AS total_TimeFormat_Error,\n  SUM(UniqueIndex_Error) AS total_UniqueIndex_Error,\n  SUM(ValueDivBy0_Error) AS total_ValueDivBy0_Error,\n  SUM(ValueNAME_Error) AS total_ValueNAME_Error,\n  SUM(ValueREF_Error) AS total_ValueREF_Error,\n  SUM(ValueVALUE_Error) AS total_ValueVALUE_Error,\n  SUM(WebService_Error) AS total_WebService_Error\nFROM dataset\nWHERE $__timeFilter(date_and_heure);"
    }
   ]
  },
  {
   "title": "Nb d'erreurs par type",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n  SUM(ColumnName_Error) as \"Daily column ColumnName_Error\",\n  SUM(ConnectionTimeout_Error) as \"Daily ConnectionTimeout_Error\",\n  SUM(CreateTABLE_Error) as \"Daily CreateTABLE_Error\",\n\n  SUM(DateFormat_Error) as \"Daily column DateFormat_Error\",\n  SUM(FieldSize_Error) as \"Daily FieldSize_Error\",\n  SUM(GuidezAtelier_Error) as \"Daily GuidezAtelier_Error\",\n\n  SUM(IndexErrorSimilarToUniqueIndex_Error) as \"Daily column IndexErrorSimilarToUniqueIndex_Error\",\n  SUM(ObjectReference_Error) as \"DailyObjectReference_Error\",\n  SUM(Other_Error) as \"Daily Other_Error\",\n\n  SUM(PreLogin_Error) as \"Daily PreLogin_Error\",\n  SUM(PrimaryKey_Error) as \"Daily PrimaryKey_Error\",\n  SUM(SQLInvalidQuery_Error) as \"Daily SQLInvalidQuery_Error\",\n\n  SUM(SQLQueryTimeout_Error) as \"Daily column SQL_QueryTimeout_Error\",\n  SUM(TimeFormat_Error) as \"Daily TimeFormat_Error\",\n  SUM(UniqueIndex_Error) as \"Daily UniqueIndex_Error\",\n\n  SUM(ValueDivBy0_Error) as \"Daily column ValueDivBy0_Error\",\n  SUM(ValueNAME_Error) as \"Daily ValueNAME_Error\",\n  SUM(ValueREF_Error) as \"Daily ValueREF_Error\",\n\n  SUM(ValueVALUE_Error) as \"Daily column ValueVALUE_Error\",\n  SUM(WebService_Error) as \"Daily WebService_Error\"\n\nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;\n\n"
    }
   ]
  },
  { "title": "Par Program_Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "NB erreurs par Program_Name",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(ETL_Achats) AS total_ETL_Achats,\n  SUM(ETL_BEXT) AS total_ETL_BEXT,\n  SUM(ETL_Chargement_PJ) AS total_ETL_Chargement_PJ,\n  SUM(ETL_GLPI) AS total_ETL_GLPI,\n  SUM(ETL_Heures_Chauffeurs) AS total_ETL_Heures_Chauffeurs,\n  SUM(ETL_JIRA) AS total_ETL_JIRA,\n  SUM(ETL_KPI_ALDI) AS total_ETL_KPI_ALDI,\n  SUM(ETL_Taxation) AS total_ETL_Taxation,\n  SUM(ETL_VUE_HEURE_AGG) AS total_ETL_VUE_HEURE_AGG,\n  SUM(ETL_SUR_ORDRE) AS total_ETL_sur_ordre,\n  SUM(ETL_API_JWT) AS total_ETL_API_JWT,\n  SUM(daily) AS total_daily,\n  SUM(WEEKLY_SUNDAY) AS total_WEEKLY_SUNDAY\nFROM dataset\nWHERE $__timeFilter(date_and_heure);"
    }
   ]
  },
  {
   "title": "Nb d'erreur par Program_Name",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n  SUM(ETL_Achats) as \"daily errors ETL_Achats\",\n  SUM(ETL_BEXT) as \"daily errors ETL_BEXT\",\n\n  SUM(ETL_Chargement_PJ) as \"daily errors ETL_Chargement_PJ\",\n  SUM(ETL_GLPI) as \"daily errors ETL_GLPI\",\n\n  SUM(ETL_Heures_Chauffeurs) as \"daily errors ETL_Heures_Chauffeurs\",\n  SUM(ETL_JIRA) as \"daily errors ETL_JIRA\",\n\n  SUM(ETL_KPI_ALDI) as \"daily errors ETL_KPI_ALDI\",\n  SUM(ETL_Taxation) as \"daily errors ETL_Taxation\",\n\n  SUM(ETL_VUE_HEURE_AGG) as \"daily errors ETL_VUE_HEURE_AGG\",\n  SUM(ETL_sur_ordre) as \"daily errors ETL_sur_ordre\",\n\n  SUM(ETL_API_JWT) as \"daily errors ETL_API_JWT\",\n  SUM(daily) as \"daily errors daily\",\n\n  SUM(WEEKLY_SUNDAY) as \"daily errors WEEKLY_SUNDAY\"\n  \nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;\n"
    }
   ]
  },
  {
   "title": "Brouillon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb d'erreurs quotidiennes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', date_and_heure::timestamp) AS jour,\n  SUM(ConnectionTimeout_Error + CreateTABLE_Error + DateFormat_Error + FieldSize_Error + Guidez_Atelier_Error + IndexErrorSimilarToUniqueIndex_Error +ObjectReference_Error + Other_Error +PreLogin_Error + PrimaryKey_Error + SQLInvalidQuery_Error + SQLQueryTimeout_Error + TimeFormat_Error + UniqueIndex_Error + ValueDIV0_Error + ValueNAME_Error + ValueREF_Error + ValueVALUE_Error + WebService_Error) AS total_erreurs\nFROM dataset\nWHERE $__timeFilter(date_and_heure)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "check avec PGADMIN",
     "type": "timeseries",
     "description": "check avec PGADMIN du nb de lignes prises en compte",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM dataset WHERE $__timeFilter(date_and_heure);"
      }
     ]
    }
   ]
  }
 ]
}