{
 "title": "ETL - jour vs. heure",
 "time": { "from": "2024-08-28T00:00:00.000Z", "to": "2024-10-15T23:59:59.000Z" },
 "panels": [
  { "title": "Nb ETL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nb ETL par jour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(DOW FROM etl_start_datetime) AS jour_semaine,\n       COUNT(*) AS nb_lignes\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY EXTRACT(DOW FROM etl_start_datetime)\nORDER BY EXTRACT(DOW FROM etl_start_datetime);"
    }
   ]
  },
  {
   "title": "Nb ETL par tranche horaire",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(HOUR FROM etl_start_datetime) AS heure_jour,\n       COUNT(*) AS nb_lignes\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY EXTRACT(HOUR FROM etl_start_datetime)\nORDER BY EXTRACT(HOUR FROM etl_start_datetime);"
    }
   ]
  },
  {
   "title": "Nb ETL par jour de la semaine et heure de la journée",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  EXTRACT(DOW FROM etl_start_datetime) AS jour_semaine,\n  EXTRACT(HOUR FROM etl_start_datetime) AS heure_jour,\n  COUNT(*) AS nb_lignes\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY jour_semaine, heure_jour\nORDER BY heure_jour, jour_semaine"
    }
   ]
  },
  {
   "title": "Nb lignes modifiées par les ETL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Nb de lignes modifiées par les ETL par jour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(DOW FROM etl_start_datetime) AS jour_semaine,\n       Sum(rows_added)+sum(rows_updated)+sum(rows_deleted) AS nb_rows_modified\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY EXTRACT(DOW FROM etl_start_datetime)\nORDER BY EXTRACT(DOW FROM etl_start_datetime);"
    }
   ]
  },
  {
   "title": "Nb lignes modifiées par les ETL par tranche horaire",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(HOUR FROM etl_start_datetime) AS heure_jour,\n       Sum(rows_added)+sum(rows_updated)+sum(rows_deleted) AS nb_rows_modified\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY EXTRACT(HOUR FROM etl_start_datetime)\nORDER BY EXTRACT(HOUR FROM etl_start_datetime);\n"
    }
   ]
  },
  {
   "title": "Nb lignes modifiées par ETL par jour de la semaine et par heure de la journée",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \n  EXTRACT(DOW FROM etl_start_datetime) AS jour_semaine,\n  EXTRACT(HOUR FROM etl_start_datetime) AS heure_jour,\n  sum(rows_added)+sum(rows_updated)+sum(rows_deleted) AS nb_lignes_modifiees\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY jour_semaine, heure_jour\nORDER BY heure_jour, jour_semaine"
    }
   ]
  },
  {
   "title": "Brouillon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb ETL par jour de semaine et heure de la journée",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 255 },
     "targets": [
      {
       "rawSql": "SELECT \n  TO_CHAR(etl_start_datetime, 'Dy') || ' ' ||\n  LPAD(EXTRACT(HOUR FROM etl_start_datetime)::text, 2, '0') || 'h' AS label,\n  COUNT(*) AS nb_lignes\nFROM logOK\nWHERE $__timeFilter(etl_start_datetime)\nGROUP BY label\nORDER BY MIN(etl_start_datetime);"
      }
     ]
    }
   ]
  }
 ]
}