{
 "title": "myreport_sql_lock dashboard",
 "time": { "from": "2024-09-06T08:30:28.885Z", "to": "2024-11-13T21:58:20.622Z" },
 "panels": [
  {
   "title": "Lock Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_heure as time, \n    AVG(nombre_requetes_verrouillage_raw) AS avg_lock_requests\nFROM myreport_sql_lock\nWHERE date_heure BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY date_heure\nORDER BY date_heure;\n"
    }
   ]
  },
  {
   "title": "Average Lock Wait Time Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_heure AS time,\n    AVG(temps_attente_moyen_raw) AS avg_lock_wait_time\nFROM myreport_sql_lock\nWHERE date_heure BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY date_heure\nORDER BY date_heure;\n"
    }
   ]
  },
  {
   "title": "Number of Blockages Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    date_heure AS time,\n    SUM(nombre_blocages_raw) AS total_blockages\nFROM myreport_sql_lock\nWHERE date_heure BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY date_heure\nORDER BY date_heure;\n"
    }
   ]
  },
  {
   "title": "SQL Lock Coverage Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        date_heure AS time,\n        couverture_raw/100 AS couverture_sql_lock_pct\n    FROM myreport_sql_lock\n)\nSELECT * \nFROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "SQL Lock Dead Time Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    date_heure AS time,\n    AVG(temps_mort_raw) AS sql_lock_dead_time_pct\nFROM myreport_sql_lock\nWHERE date_heure BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;"
    }
   ]
  }
 ]
}