{
 "title": "myreport_reseau dashboard",
 "time": { "from": "2024-08-20T22:00:00.000Z", "to": "2024-11-13T22:59:59.000Z" },
 "panels": [
  {
   "title": "Incoming vs. Outgoing Non-Monodiffusion Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(paquets_non_monodiffusion_entrants_volume_raw) AS non_monodiffusion_incoming_packets,\n    SUM(paquets_non_monodiffusion_sortants_volume_raw) AS non_monodiffusion_outgoing_packets\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day'))\n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Comparison of Actual vs. 6-Day Moving Average for Incoming and Outgoing Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')) AS time,\n    \n    AVG(trafic_entrant_debit_raw) / (1024*1024) AS \"Average Incoming Traffic Speed (Mbps)\",\n    AVG(trafic_sortant_debit_raw) / (1024*1024) AS \"Average Outgoing Traffic Speed (Mbps)\",\n    \n    AVG(AVG(trafic_entrant_debit_raw) / (1024*1024)) \n        OVER (PARTITION BY 1 ORDER BY DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI'))) \n        AS \"6-Day Moving Average of Incoming Speed (Mbps)\",\n    \n    AVG(AVG(trafic_sortant_debit_raw) / (1024*1024)) \n        OVER (PARTITION BY 1 ORDER BY DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI'))) \n        AS \"6-Day Moving Average of Outgoing Speed (Mbps)\"\n    \nFROM myreport_reseau\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Incoming and Outgoing Mono-diffusion Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(monodiffusion_entrante_volume_raw) AS monodiffusion_incoming_mb,\n    SUM(monodiffusion_sortante_volume_raw) AS monodiffusion_outgoing_mb\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day'))\n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Peak Traffic Analysis (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')) AS time,\n    MAX(trafic_entrant_volume_raw)/1048576 AS max_incoming_traffic_MB,\n    MAX(trafic_sortant_volume_raw)/1048576 AS max_outgoing_traffic_MB\nFROM myreport_reseau\nGROUP BY time\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Network Traffic (Incoming vs Outgoing in MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', \n        TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')\n    ) AS time,\n    SUM(trafic_entrant_volume_raw)/1048576 AS incoming_traffic,\n    SUM(trafic_sortant_volume_raw)/1048576 AS outgoing_traffic\nFROM myreport_reseau\nWHERE \n    TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')\n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Network Errors Over Time (Incoming vs Outgoing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(erreurs_entrantes_volume_raw) AS incoming_errors,\n    SUM(erreurs_sortantes_volume_raw) AS outgoing_errors\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Network Coverage Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(couverture_raw)/100 AS network_coverage\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day'))\n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Errors vs Successful Packets ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(erreurs_entrantes_volume_raw + erreurs_sortantes_volume_raw) AS total_errors,\n    SUM(paquets_volume_raw) AS successful_packets\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Bandwidth Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(trafic_entrant_debit_raw + trafic_sortant_debit_raw)/86400 AS total_bandwidth_usage\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Unknown Protocol Activity Over Time (Incoming)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(protocoles_inconnus_entrants_volume_raw) AS unknown_incoming_protocols\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Total Network Traffic Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(trafic_entrant_volume_raw + trafic_sortant_volume_raw)/1024/1024 AS total_network_trafic\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Total Packets Sent Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(paquets_volume_raw) AS total_packets\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Rejected Packets Over Time (Incoming & Outgoing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(entrants_rejets_volume_raw) AS incoming_rejected_packets,\n    SUM(sortants_rejets_volume_raw) AS outgoing_rejected_packets\nFROM myreport_reseau\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  }
 ]
}