{
 "title": "myreport_espace_disque",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Utilisation moyenne de l’espace disque par jour (Go)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('day', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n    AVG(somme_raw / 1024 / 1024 / 1024) AS avg_used_space_gb\nFROM myreport_espace_disque\nWHERE TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS') \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Consommation horaire de l'espace disque (Go)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        DATE_TRUNC('hour', \n            TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')\n        ) AS time,\n        (somme_raw / 1024 / 1024 / 1024) AS \"Espace utilisé (Go)\" -- Convert bytes to GB\n    FROM myreport_espace_disque\n)\nSELECT * \nFROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Évolution de l'espace disque utilisé et disponible (Go)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS') AS time,\n        somme_raw / 1024 / 1024 / 1024 AS used_space_GB,  -- Conversion en Go\n        octetlibrec_raw / 1024 / 1024 / 1024 AS free_space_GB  -- Conversion en Go\n    FROM myreport_espace_disque\n)\nSELECT * FROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Consommation d’espace disque en Go",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS') AS time,\n        somme_raw / 1024 / 1024 / 1024 AS used_space_gb  -- Convert bytes to GB\n    FROM myreport_espace_disque\n)\nSELECT * \nFROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n\n"
    }
   ]
  }
 ]
}