{
 "title": "myreport_ping dashboard",
 "time": { "from": "2024-08-28T13:21:32.356Z", "to": "2024-11-16T03:49:34.017Z" },
 "panels": [
  {
   "title": "Packet Loss Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(perte_de_paquets_raw) AS packet_loss_rate\nFROM myreport_ping\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Packet Loss Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    'Packet Loss Rate (%)' AS category,\n    AVG(perte_de_paquets_raw) AS value\nFROM myreport_ping;\n"
    }
   ]
  },
  {
   "title": "Ping Response Time Analysis (Min, Avg, Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(temps_du_ping_raw) AS avg_ping_time_ms,\n    MIN(minimum_raw) AS min_ping_time_ms,\n    MAX(maximum_raw) AS max_ping_time_ms\nFROM myreport_ping\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Network Downtime Trends Over Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    SUM(temps_mort_raw) AS total_downtime_seconds\nFROM myreport_ping\nGROUP BY time\nORDER BY time;"
    }
   ]
  }
 ]
}