{
 "title": "myreport_cpu dashboard",
 "time": { "from": "2024-08-20T22:00:00.000Z", "to": "2024-11-13T22:59:59.000Z" },
 "panels": [
  {
   "title": "Utilisation moyenne quotidienne du CPU par processeur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        DATE_TRUNC('day', TO_TIMESTAMP(SPLIT_PART(CAST(date AS TEXT), ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        AVG(processeur_1_raw) AS processeur_1,\n        AVG(processeur_2_raw) AS processeur_2,\n        AVG(processeur_3_raw) AS processeur_3,\n        AVG(processeur_4_raw) AS processeur_4,\n        AVG(processeur_5_raw) AS processeur_5,\n        AVG(processeur_6_raw) AS processeur_6,\n        AVG(processeur_7_raw) AS processeur_7,\n        AVG(processeur_8_raw) AS processeur_8\n    FROM myreport_cpu\n    GROUP BY 1\n)\nSELECT * FROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Analyse horaire de l'utilisation du CPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 1' AS processeur, processeur_1_raw AS utilisation_cpu FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 2', processeur_2_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 3', processeur_3_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 4', processeur_4_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 5', processeur_5_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 6', processeur_6_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 7', processeur_7_raw FROM myreport_cpu\n    UNION ALL\n    SELECT \n        DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' - ', 1), 'DD/MM/YYYY HH24:MI:SS')) AS time,\n        'Processeur 8', processeur_8_raw FROM myreport_cpu\n)\nSELECT * FROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n\n\n"
    }
   ]
  },
  {
   "title": "Couverture du CPU au fil du temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH formatted_data AS (\n    SELECT \n        TO_TIMESTAMP(SPLIT_PART(CAST(date AS TEXT), ' - ', 1), 'DD/MM/YYYY HH24:MI:SS') AS time,\n        couverture_cpu_raw/10000\n    FROM myreport_cpu\n)\nSELECT * \nFROM formatted_data\nWHERE $__timeFilter(time)\nORDER BY time;\n"
    }
   ]
  }
 ]
}