{
 "title": "MyReport Synthèse",
 "time": { "from": "2024-10-01T23:29:48.508Z", "to": "2024-10-02T02:09:24.338Z" },
 "panels": [
  {
   "title": "RAM free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT date_heure, SUM(memoire_disponible_go_raw) FROM myreport_ram GROUP BY date_heure LIMIT 50 "
    }
   ]
  },
  {
   "title": "trafic réseau",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_heure, \n  AVG(trafic_sortant_volume_raw)*(-1) as \"volume sortant\", \n  AVG(trafic_entrant_volume_raw) as \"volume entrant\"\nFROM myreport_reseau \nGROUP BY date_heure \nORDER BY date_heure\n"
    }
   ]
  },
  {
   "title": "Charge CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT date_heure,\nAVG(processeur_1_raw) as core1, \nAVG(processeur_2_raw) as core2, \nAVG(processeur_3_raw)  as core3, \nAVG(processeur_4_raw)  as core4, \nAVG(processeur_5_raw) as core5, \nAVG(processeur_6_raw) as core6, \nAVG(processeur_7_raw) as core7,\nAVG(processeur_8_raw) as core8\n\nFROM myreport_cpu GROUP BY date_heure\norder by date_heure"
    }
   ]
  },
  {
   "title": "Utilisation du swap (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT date_heure, \nAVG(total_raw) as Swap\n\nFROM myreport_swap GROUP BY date_heure"
    }
   ]
  }
 ]
}