{
 "title": "myreport_sql_statistic dashboard",
 "time": { "from": "2024-08-20T22:00:00.000Z", "to": "2024-11-13T22:59:59.000Z" },
 "panels": [
  {
   "title": "SQL Requests Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(nombre_requetes_lots_raw) AS avg_requetes_lots\nFROM myreport_sql_statistic\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "SQL Recompilations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(recompilations_sql_raw) AS avg_recompilations_per_sec\nFROM myreport_sql_statistic\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) \n    BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "SQL Query Execution Trends ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')) AS time,\n    SUM(nombre_requetes_lots_raw) AS total_queries,\n    SUM(compilations_sql_raw) AS total_compilations,\n    SUM(recompilations_sql_raw) AS total_recompilations\nFROM myreport_sql_statistic\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "SQL Coverage Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('day', TO_TIMESTAMP(SPLIT_PART(date_heure, ' ', 1) || ' ' || SPLIT_PART(date_heure, ' ', 3), 'DD/MM/YYYY HH24:MI')) AS day,\n    AVG(couverture_raw)/100 AS avg_coverage\nFROM myreport_sql_statistic\nGROUP BY day\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "SQL Statistics Dead Time Over Time (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \n    DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day')) AS time,\n    AVG(temps_mort_raw) AS sql_statistic_dead_time\nFROM myreport_sql_statistic\nWHERE DATE_TRUNC('hour', TIMESTAMP '1900-01-01' + (date_heure_raw * INTERVAL '1 day'))\n      BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY time\nORDER BY time;"
    }
   ]
  }
 ]
}