{
 "title": "Mon premier dashboard",
 "time": { "from": "2024-08-28T06:00:51.000Z", "to": "2024-10-15T10:58:53.000Z" },
 "panels": [
  {
   "title": "Nb erreurs quotidiennes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb erreurs quotidiennes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Nb erreurs quotidiennes (échelle log10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  {
   "title": "Nb erreurs hebdo (7j glissants)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb erreurs totales sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Nb erreurs totales sur 7 jours glissants (échelle log10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  {
   "title": "Taux d'erreur quotidien",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Taux d'erreur quotidien global",
     "type": "timeseries",
     "description": "SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n   SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations))\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  ) AS ratio_7j\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 30 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '29 days' PRECEDING AND CURRENT ROW\n  ) AS ratio_7j\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  { "title": "Général", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "NB erreurs par Program_Name",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT 'ETL Achats' AS etl_type, SUM(COALESCE(ETL_Achats, 0)) AS total FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL BEXT', SUM(COALESCE(ETL_BEXT, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Chargement PJ', SUM(COALESCE(ETL_Chargement_PJ, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL GLPI', SUM(COALESCE(ETL_GLPI, 0)) FROM dataset\nUNION ALL\nSELECT 'ETL Heures Chauffeurs', SUM(COALESCE(ETL_Heures_Chauffeurs, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL JIRA', SUM(COALESCE(ETL_JIRA, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL KPI ALDI', SUM(COALESCE(ETL_KPI_ALDI, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Taxation', SUM(COALESCE(ETL_Taxation, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Vue Heures Agrégées', SUM(COALESCE(ETL_Vue_Heures_Agregees, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL sur ordre', SUM(COALESCE(ETL_sur_ordre, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL_API_JWT', SUM(COALESCE(ETL_API_JWT, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Tous les jours', SUM(COALESCE(Tous_les_jours, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Toutes les semaines, le dimanche', SUM(COALESCE(Toutes_les_semaines_le_dimanche, 0)) FROM dataset WHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Répartition par type d'erreus",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT 'Connection_Timeout_Error' AS error_type, SUM(COALESCE(Connection_Timeout_Error, 0)) AS total FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Create_TABLE_Error', SUM(COALESCE(Create_TABLE_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Date_Format_Error', SUM(COALESCE(Date_Format_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Field_Size_Error', SUM(COALESCE(Field_Size_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Guidez_Atelier_Error', SUM(COALESCE(Guidez_Atelier_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Index_Error', SUM(COALESCE(Index_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Object_Reference_Error', SUM(COALESCE(Object_Reference_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Other_Error', SUM(COALESCE(Other_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Pre_Login_Error', SUM(COALESCE(Pre_Login_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Primary_Key_Error', SUM(COALESCE(Primary_Key_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'SQL_Invalid_Query_Error', SUM(COALESCE(SQL_Invalid_Query_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'SQL_Query_Timeout_Error', SUM(COALESCE(SQL_Query_Timeout_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Time_Format_Error', SUM(COALESCE(Time_Format_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Unique_Index_Error', SUM(COALESCE(Unique_Index_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_DIV0_Error', SUM(COALESCE(Value_DIV0_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_NAME_Error', SUM(COALESCE(Value_NAME_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_REF_Error', SUM(COALESCE(Value_REF_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_VALUE_Error', SUM(COALESCE(Value_VALUE_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Web_Service_Error', SUM(COALESCE(Web_Service_Error, 0)) FROM dataset WHERE $__timeFilter(time);"
    }
   ]
  },
  { "title": "Performance globale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Nb d'erreurs quotidiennes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(Connection_Timeout_Error + Create_TABLE_Error + Date_Format_Error + Field_Size_Error + Guidez_Atelier_Error + Index_Error + Object_Reference_Error + Other_Error + Pre_Login_Error + Primary_Key_Error + SQL_Invalid_Query_Error + SQL_Query_Timeout_Error + Time_Format_Error + Unique_Index_Error + Value_DIV0_Error + Value_NAME_Error + Value_REF_Error + Value_VALUE_Error + Web_Service_Error) AS total_erreurs\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  }
 ]
}