{
 "title": "Mon premier dashboard",
 "time": { "from": "2024-08-28T06:00:51.000Z", "to": "2024-10-15T10:58:53.000Z" },
 "panels": [
  { "title": "Nb erreurs quotidiennes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nb erreurs quotidiennes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Nb erreurs quotidiennes (échelle log10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
    }
   ]
  },
  {
   "title": "Nb erreurs hebdo (7j glissants)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb erreurs totales sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Nb erreurs totales sur 7 jours glissants (échelle log10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  {
   "title": "Taux d'erreur quotidien",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Taux d'erreur quotidien global",
     "type": "timeseries",
     "description": "SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n   SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations)) as \"taux d'erreur\"\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 7j\"\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 30 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '29 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 30j\"\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  { "title": "Par type d'erreu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Répartition par type d'erreur",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT 'Column_Name_Error' AS error_type, SUM(COALESCE(Column_Name_Error, 0)) AS total FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Connection_Timeout_Error' AS error_type, SUM(COALESCE(Connection_Timeout_Error, 0)) AS total FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Create_TABLE_Error', SUM(COALESCE(Create_TABLE_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Date_Format_Error', SUM(COALESCE(Date_Format_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Field_Size_Error', SUM(COALESCE(Field_Size_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Guidez_Atelier_Error', SUM(COALESCE(Guidez_Atelier_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Index_Error', SUM(COALESCE(Index_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Object_Reference_Error', SUM(COALESCE(Object_Reference_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Other_Error', SUM(COALESCE(Other_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Pre_Login_Error', SUM(COALESCE(Pre_Login_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Primary_Key_Error', SUM(COALESCE(Primary_Key_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'SQL_Invalid_Query_Error', SUM(COALESCE(SQL_Invalid_Query_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'SQL_Query_Timeout_Error', SUM(COALESCE(SQL_Query_Timeout_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Time_Format_Error', SUM(COALESCE(Time_Format_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Unique_Index_Error', SUM(COALESCE(Unique_Index_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_DIV0_Error', SUM(COALESCE(Value_DIV0_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_NAME_Error', SUM(COALESCE(Value_NAME_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_REF_Error', SUM(COALESCE(Value_REF_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Value_VALUE_Error', SUM(COALESCE(Value_VALUE_Error, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Web_Service_Error', SUM(COALESCE(Web_Service_Error, 0)) FROM dataset WHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Nb d'erreurs par type",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(Column_Name_Error) as \"Daily column Column_Name_Error\",\n  SUM(Connection_Timeout_Error) as \"Daily Connection_Timeout_Error\",\n  SUM(Create_TABLE_Error) as \"Daily Create_TABLE_Error\",\n\n  SUM(Date_Format_Error) as \"Daily column Date_Format_Error\",\n  SUM(Field_Size_Error) as \"Daily Field_Size_Error\",\n  SUM(Guidez_Atelier_Error) as \"Daily Guidez_Atelier_Error\",\n\n  SUM(Index_Error) as \"Daily column Index_Error\",\n  SUM(Object_Reference_Error) as \"Daily Object_Reference_Error\",\n  SUM(Other_Error) as \"Daily Other_Error\",\n\n  SUM(Pre_Login_Error) as \"Daily column Pre_Login_Error\",\n  SUM(Primary_Key_Error) as \"Daily Primary_Key_Error\",\n  SUM(SQL_Invalid_Query_Error) as \"Daily SQL_Invalid_Query_Error\",\n\n  SUM(SQL_Query_Timeout_Error) as \"Daily column SQL_Query_Timeout_Error\",\n  SUM(Time_Format_Error) as \"Daily Time_Format_Error\",\n  SUM(Unique_Index_Error) as \"Daily Unique_Index_Error\",\n\n  SUM(Value_DIV0_Error) as \"Daily column Value_DIV0_Error\",\n  SUM(Value_NAME_Error) as \"Daily Value_NAME_Error\",\n  SUM(Value_REF_Error) as \"Daily Value_REF_Error\",\n\n  SUM(Value_VALUE_Error) as \"Daily column Value_VALUE_Error\",\n  SUM(Web_Service_Error) as \"Daily Web_Service_Error\"\n\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;\n\n"
    }
   ]
  },
  { "title": "Par Program_Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "NB erreurs par Program_Name",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT 'ETL Achats' AS etl_type, SUM(COALESCE(ETL_Achats, 0)) AS total FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL BEXT', SUM(COALESCE(ETL_BEXT, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Chargement PJ', SUM(COALESCE(ETL_Chargement_PJ, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL GLPI', SUM(COALESCE(ETL_GLPI, 0)) FROM dataset\nUNION ALL\nSELECT 'ETL Heures Chauffeurs', SUM(COALESCE(ETL_Heures_Chauffeurs, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL JIRA', SUM(COALESCE(ETL_JIRA, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL KPI ALDI', SUM(COALESCE(ETL_KPI_ALDI, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Taxation', SUM(COALESCE(ETL_Taxation, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL Vue Heures Agrégées', SUM(COALESCE(ETL_Vue_Heures_Agregees, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL sur ordre', SUM(COALESCE(ETL_sur_ordre, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'ETL_API_JWT', SUM(COALESCE(ETL_API_JWT, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Tous les jours', SUM(COALESCE(Tous_les_jours, 0)) FROM dataset WHERE $__timeFilter(time)\nUNION ALL\nSELECT 'Toutes les semaines, le dimanche', SUM(COALESCE(Toutes_les_semaines_le_dimanche, 0)) FROM dataset WHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Nb d'erreur par Program_Name",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(ETL_Achats) as \"daily errors ETL_Achats\",\n  SUM(ETL_BEXT) as \"daily errors ETL_BEXT\",\n\n  SUM(ETL_Chargement_PJ) as \"daily errors ETL_Chargement_PJ\",\n  SUM(ETL_GLPI) as \"daily errors ETL_GLPI\",\n\n  SUM(ETL_Heures_Chauffeurs) as \"daily errors ETL_Heures_Chauffeurs\",\n  SUM(ETL_JIRA) as \"daily errors ETL_JIRA\",\n\n  SUM(ETL_KPI_ALDI) as \"daily errors ETL_KPI_ALDI\",\n  SUM(ETL_Taxation) as \"daily errors ETL_Taxation\",\n\n  SUM(ETL_Vue_Heures_Agregees) as \"daily errors ETL_Vue_Heures_Agregees\",\n  SUM(ETL_sur_ordre) as \"daily errors ETL_sur_ordre\",\n\n  SUM(ETL_API_JWT) as \"daily errors ETL_API_JWT\",\n  SUM(Tous_les_jours) as \"daily errors Tous_les_jours\",\n\n  SUM(Toutes_les_semaines_le_dimanche) as \"daily errors Toutes_les_semaines_le_dimanche\"\n  \nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;\n"
    }
   ]
  },
  {
   "title": "Brouillon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb d'erreurs quotidiennes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(Connection_Timeout_Error + Create_TABLE_Error + Date_Format_Error + Field_Size_Error + Guidez_Atelier_Error + Index_Error + Object_Reference_Error + Other_Error + Pre_Login_Error + Primary_Key_Error + SQL_Invalid_Query_Error + SQL_Query_Timeout_Error + Time_Format_Error + Unique_Index_Error + Value_DIV0_Error + Value_NAME_Error + Value_REF_Error + Value_VALUE_Error + Web_Service_Error) AS total_erreurs\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    }
   ]
  }
 ]
}