{
 "title": "Mon premier dashboard",
 "time": { "from": "2024-10-14T22:00:00.000Z", "to": "2024-10-15T21:59:59.000Z" },
 "panels": [
  {
   "title": "Nb erreurs quotidiennes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb erreurs quotidiennes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Nb erreurs quotidiennes (échelle log10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM( total_errors)\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  {
   "title": "Nb erreurs hebdo (7j glissants)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb erreurs totales sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Nb erreurs totales sur 7 jours glissants (échelle log10)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors\n  FROM dataset\n  -- Optionnel : si vous souhaitez tout de même limiter la période globale\n  -- WHERE time >= now() - interval '30 days'\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- On additionne sur les 6 jours précédents + le jour courant\n  SUM(sum_errors) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  )\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  {
   "title": "Taux d'erreur quotidien",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Taux d'erreur quotidien global",
     "type": "timeseries",
     "description": "SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations))",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n   SUM(total_errors)/(SUM(total_errors)+SUM(nb_operations)) as \"taux d'erreur\"\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 7 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '6 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 7j\"\nFROM daily\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "Taux d'erreur quotidien MOYEN sur 30 jours glissants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "WITH daily AS (\n  SELECT\n    date_trunc('day', time)::date AS jour, \n    SUM(total_errors)::float AS sum_errors,\n    SUM(nb_operations)::float AS sum_ops,\n    -- Taux quotidien pour chaque jour\n    SUM(total_errors)::float / (SUM(total_errors)::float + SUM(nb_operations)::float) AS daily_ratio\n  FROM dataset\n  GROUP BY 1\n)\nSELECT\n  jour,\n  -- Moyenne des daily_ratio sur les 7 derniers jours (jour courant + les 6 jours précédents)\n  AVG(daily_ratio) OVER (\n    ORDER BY jour\n    RANGE BETWEEN '29 days' PRECEDING AND CURRENT ROW\n  ) AS \"taux d'erreur moyen 30j\"\nFROM daily\nORDER BY jour;"
      }
     ]
    }
   ]
  },
  { "title": "Par type d'erreu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Répartition par type d'erreur",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(Column_Name_Error) AS total_Column_Name_Error,\n  SUM(Connection_Timeout_Error) AS total_Connection_Timeout_Error,\n  SUM(Create_TABLE_Error) AS total_Create_TABLE_Error,\n  SUM(Date_Format_Error) AS total_Date_Format_Error,\n  SUM(Field_Size_Error) AS total_Field_Size_Error,\n  SUM(Guidez_Atelier_Error) AS total_Guidez_Atelier_Error,\n  SUM(Index_Error) AS total_Index_Error,\n  SUM(Object_Reference_Error) AS total_Object_Reference_Error,\n  SUM(Other_Error) AS total_Other_Error,\n  SUM(Pre_Login_Error) AS total_Pre_Login_Error,\n  SUM(Primary_Key_Error) AS total_Primary_Key_Error,\n  SUM(SQL_Invalid_Query_Error) AS total_SQL_Invalid_Query_Error,\n  SUM(SQL_Query_Timeout_Error) AS total_SQL_Query_Timeout_Error,\n  SUM(Time_Format_Error) AS total_Time_Format_Error,\n  SUM(Unique_Index_Error) AS total_Unique_Index_Error,\n  SUM(Value_DIV0_Error) AS total_Value_DIV0_Error,\n  SUM(Value_NAME_Error) AS total_Value_NAME_Error,\n  SUM(Value_REF_Error) AS total_Value_REF_Error,\n  SUM(Value_VALUE_Error) AS total_Value_VALUE_Error,\n  SUM(Web_Service_Error) AS total_Web_Service_Error\nFROM dataset\nWHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Nb d'erreurs par type",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(Column_Name_Error) as \"Daily column Column_Name_Error\",\n  SUM(Connection_Timeout_Error) as \"Daily Connection_Timeout_Error\",\n  SUM(Create_TABLE_Error) as \"Daily Create_TABLE_Error\",\n\n  SUM(Date_Format_Error) as \"Daily column Date_Format_Error\",\n  SUM(Field_Size_Error) as \"Daily Field_Size_Error\",\n  SUM(Guidez_Atelier_Error) as \"Daily Guidez_Atelier_Error\",\n\n  SUM(Index_Error) as \"Daily column Index_Error\",\n  SUM(Object_Reference_Error) as \"Daily Object_Reference_Error\",\n  SUM(Other_Error) as \"Daily Other_Error\",\n\n  SUM(Pre_Login_Error) as \"Daily column Pre_Login_Error\",\n  SUM(Primary_Key_Error) as \"Daily Primary_Key_Error\",\n  SUM(SQL_Invalid_Query_Error) as \"Daily SQL_Invalid_Query_Error\",\n\n  SUM(SQL_Query_Timeout_Error) as \"Daily column SQL_Query_Timeout_Error\",\n  SUM(Time_Format_Error) as \"Daily Time_Format_Error\",\n  SUM(Unique_Index_Error) as \"Daily Unique_Index_Error\",\n\n  SUM(Value_DIV0_Error) as \"Daily column Value_DIV0_Error\",\n  SUM(Value_NAME_Error) as \"Daily Value_NAME_Error\",\n  SUM(Value_REF_Error) as \"Daily Value_REF_Error\",\n\n  SUM(Value_VALUE_Error) as \"Daily column Value_VALUE_Error\",\n  SUM(Web_Service_Error) as \"Daily Web_Service_Error\"\n\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;\n\n"
    }
   ]
  },
  { "title": "Par Program_Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "NB erreurs par Program_Name",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(ETL_Achats) AS total_ETL_Achats,\n  SUM(ETL_BEXT) AS total_ETL_BEXT,\n  SUM(ETL_Chargement_PJ) AS total_ETL_Chargement_PJ,\n  SUM(ETL_GLPI) AS total_ETL_GLPI,\n  SUM(ETL_Heures_Chauffeurs) AS total_ETL_Heures_Chauffeurs,\n  SUM(ETL_JIRA) AS total_ETL_JIRA,\n  SUM(ETL_KPI_ALDI) AS total_ETL_KPI_ALDI,\n  SUM(ETL_Taxation) AS total_ETL_Taxation,\n  SUM(ETL_Vue_Heures_Agregees) AS total_ETL_Vue_Heures_Agregees,\n  SUM(ETL_sur_ordre) AS total_ETL_sur_ordre,\n  SUM(ETL_API_JWT) AS total_ETL_API_JWT,\n  SUM(Tous_les_jours) AS total_Tous_les_jours,\n  SUM(Toutes_les_semaines_le_dimanche) AS total_Toutes_les_semaines_le_dimanche\nFROM dataset\nWHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Nb d'erreur par Program_Name",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(ETL_Achats) as \"daily errors ETL_Achats\",\n  SUM(ETL_BEXT) as \"daily errors ETL_BEXT\",\n\n  SUM(ETL_Chargement_PJ) as \"daily errors ETL_Chargement_PJ\",\n  SUM(ETL_GLPI) as \"daily errors ETL_GLPI\",\n\n  SUM(ETL_Heures_Chauffeurs) as \"daily errors ETL_Heures_Chauffeurs\",\n  SUM(ETL_JIRA) as \"daily errors ETL_JIRA\",\n\n  SUM(ETL_KPI_ALDI) as \"daily errors ETL_KPI_ALDI\",\n  SUM(ETL_Taxation) as \"daily errors ETL_Taxation\",\n\n  SUM(ETL_Vue_Heures_Agregees) as \"daily errors ETL_Vue_Heures_Agregees\",\n  SUM(ETL_sur_ordre) as \"daily errors ETL_sur_ordre\",\n\n  SUM(ETL_API_JWT) as \"daily errors ETL_API_JWT\",\n  SUM(Tous_les_jours) as \"daily errors Tous_les_jours\",\n\n  SUM(Toutes_les_semaines_le_dimanche) as \"daily errors Toutes_les_semaines_le_dimanche\"\n  \nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;\n"
    }
   ]
  },
  {
   "title": "Brouillon",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nb d'erreurs quotidiennes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', time::timestamp) AS jour,\n  SUM(Connection_Timeout_Error + Create_TABLE_Error + Date_Format_Error + Field_Size_Error + Guidez_Atelier_Error + Index_Error + Object_Reference_Error + Other_Error + Pre_Login_Error + Primary_Key_Error + SQL_Invalid_Query_Error + SQL_Query_Timeout_Error + Time_Format_Error + Unique_Index_Error + Value_DIV0_Error + Value_NAME_Error + Value_REF_Error + Value_VALUE_Error + Web_Service_Error) AS total_erreurs\nFROM dataset\nWHERE $__timeFilter(time)\nGROUP BY jour\nORDER BY jour;"
      }
     ]
    },
    {
     "title": "check avec PGADMIN",
     "type": "timeseries",
     "description": "check avec PGADMIN du nb de lignes prises en compte",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM dataset WHERE $__timeFilter(time);"
      }
     ]
    }
   ]
  }
 ]
}