apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    url: postgres:5432
    user: admin
    secureJsonData:
      password: 'admin'
    uid: "dedjfow6t58n4e"
    jsonData:
      database: postgres
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 150 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
